ORCHESTRATOR_VERSION = "1.0.0"
EVENT_CONTRACT_VERSION = "1.0.0"
OUTBOX_VERSION = "1.0.0"
SYSTEM_STATUS_CONTRACT_VERSION = "1.0.0"

# Automation States
AUTOMATION_PAUSED = "PAUSED"
AUTOMATION_RUNNING = "RUNNING"
AUTOMATION_EMERGENCY_STOPPED = "EMERGENCY_STOPPED"

# Execution Modes
MODE_CONFIRMATION = "CONFIRMATION"
MODE_AUTOMATIC = "AUTOMATIC"

# Orchestration Run Statuses
RUN_STATUS_RECEIVED = "RECEIVED"
RUN_STATUS_RUNNING = "RUNNING"
RUN_STATUS_WAITING = "WAITING"
RUN_STATUS_SUCCEEDED = "SUCCEEDED"
RUN_STATUS_BLOCKED = "BLOCKED"
RUN_STATUS_FAILED = "FAILED"
RUN_STATUS_CANCELLED = "CANCELLED"

# Orchestration Step Statuses
STEP_STATUS_PENDING = "PENDING"
STEP_STATUS_RUNNING = "RUNNING"
STEP_STATUS_SUCCEEDED = "SUCCEEDED"
STEP_STATUS_SKIPPED = "SKIPPED"
STEP_STATUS_BLOCKED = "BLOCKED"
STEP_STATUS_FAILED = "FAILED"

# Control Phrases
EMERGENCY_RESET_PHRASE = "RESET EMERGENCY STOP"
DEMO_TRADING_ENABLE_PHRASE = "ENABLE DEMO XAUUSD TRADING"
