PARSER_VERSION = "1.0.0"
CONTRACT_VERSION = "1.0.0"

SUPPORTED_INSTRUMENTS = {"XAUUSD", "GOLD", "XAU/USD", "XAU USD"}
UNSUPPORTED_INSTRUMENTS = {"BTCUSD", "EURUSD", "US30", "NAS100", "GBPUSD", "SILVER", "XAGUSD"}

DIRECTION_BUY = "BUY"
DIRECTION_SELL = "SELL"

ORDER_INTENT_LIMIT = "LIMIT"
ORDER_INTENT_UNSPECIFIED = "UNSPECIFIED"

UNICODE_DASHES = ["-", "–", "—", "−", "‐", "‑"]
