export const DESKTOP_VERSION = "1.0.0";
export const DASHBOARD_CONTRACT_VERSION = "1.0.0";
export const DESKTOP_EVENT_CLIENT_VERSION = "1.0.0";

export const DEFAULT_FASTAPI_URL = "http://127.0.0.1:8000";
export const DEFAULT_WORKER_URL = "http://127.0.0.1:8010";

export const CONTROL_PHRASES = {
  ENABLE_DEMO: "ENABLE DEMO XAUUSD TRADING",
  EMERGENCY_STOP: "EMERGENCY STOP XAUUSD",
  RESET_EMERGENCY_STOP: "RESET EMERGENCY STOP",
  CLOSE_ALL_DEMO: "CLOSE ALL DEMO XAUUSD",
  RESET_WHATSAPP: "RESET WHATSAPP SESSION",
};

export const MAX_EXPOSURE_LOTS = 2.0000;
export const MAX_ENTRIES = 8;
