STATE_MACHINE_VERSION = "1.0.0"
DUPLICATE_STRATEGY_VERSION = "1.0.0"

# Campaign Wire States
STATE_RECEIVED = "RECEIVED"
STATE_PARSED = "PARSED"
STATE_INVALID = "INVALID"
STATE_WAITING_FOR_TP = "WAITING_FOR_TP"
STATE_AWAITING_CONFIRMATION = "AWAITING_CONFIRMATION"
STATE_PLANNED = "PLANNED"
STATE_PLACING_ORDERS = "PLACING_ORDERS"
STATE_PARTIALLY_PLACED = "PARTIALLY_PLACED"
STATE_PENDING = "PENDING"
STATE_PARTIALLY_FILLED = "PARTIALLY_FILLED"
STATE_OPEN = "OPEN"
STATE_MANAGING = "MANAGING"
STATE_CLOSING = "CLOSING"
STATE_CLOSED = "CLOSED"
STATE_CANCELLED = "CANCELLED"
STATE_REJECTED = "REJECTED"
STATE_FAILED = "FAILED"

ALL_CAMPAIGN_STATES = {
    STATE_RECEIVED, STATE_PARSED, STATE_INVALID, STATE_WAITING_FOR_TP,
    STATE_AWAITING_CONFIRMATION, STATE_PLANNED, STATE_PLACING_ORDERS,
    STATE_PARTIALLY_PLACED, STATE_PENDING, STATE_PARTIALLY_FILLED, STATE_OPEN,
    STATE_MANAGING, STATE_CLOSING, STATE_CLOSED, STATE_CANCELLED, STATE_REJECTED, STATE_FAILED
}

TERMINAL_STATES = {STATE_INVALID, STATE_CLOSED, STATE_CANCELLED, STATE_REJECTED, STATE_FAILED}
ACTIVE_CAMPAIGN_STATES = {STATE_WAITING_FOR_TP, STATE_AWAITING_CONFIRMATION, STATE_PLANNED, STATE_PENDING, STATE_PARTIALLY_FILLED, STATE_OPEN, STATE_MANAGING}

# Prompt 5 Valid Transition Matrix
ALLOWED_TRANSITIONS = {
    STATE_RECEIVED: {STATE_PARSED, STATE_INVALID},
    STATE_PARSED: {STATE_WAITING_FOR_TP, STATE_AWAITING_CONFIRMATION, STATE_INVALID},
    STATE_WAITING_FOR_TP: {STATE_WAITING_FOR_TP, STATE_AWAITING_CONFIRMATION, STATE_CANCELLED, STATE_REJECTED, STATE_FAILED},
    STATE_AWAITING_CONFIRMATION: {STATE_AWAITING_CONFIRMATION, STATE_PLANNED, STATE_CANCELLED, STATE_REJECTED, STATE_FAILED},
    STATE_PLANNED: {STATE_CANCELLED, STATE_FAILED},
}

# Reason Codes
REASON_SIGNAL_RECEIVED = "SIGNAL_RECEIVED"
REASON_SIGNAL_PARSED = "SIGNAL_PARSED"
REASON_SIGNAL_INVALID = "SIGNAL_INVALID"
REASON_MISSING_TAKE_PROFIT = "MISSING_TAKE_PROFIT"
REASON_SIGNAL_COMPLETE = "SIGNAL_COMPLETE"
REASON_USER_APPROVED = "USER_APPROVED"
REASON_USER_REJECTED = "USER_REJECTED"
REASON_ADMIN_CANCELLED = "ADMIN_CANCELLED"
REASON_ADMIN_CLOSE_REQUESTED = "ADMIN_CLOSE_REQUESTED"
REASON_TP_UPDATE_RECEIVED = "TP_UPDATE_RECEIVED"
REASON_ZONE_VALID_RECEIVED = "ZONE_VALID_RECEIVED"
REASON_AMBIGUOUS_COMMAND_REQUIRES_CONFIRMATION = "AMBIGUOUS_COMMAND_REQUIRES_CONFIRMATION"
REASON_DUPLICATE_BLOCKED = "DUPLICATE_BLOCKED"
REASON_SEMANTIC_DUPLICATE_BLOCKED = "SEMANTIC_DUPLICATE_BLOCKED"
REASON_EXPLICIT_REENTRY_CREATED = "EXPLICIT_REENTRY_CREATED"
REASON_PERSISTENCE_FAILURE = "PERSISTENCE_FAILURE"

# Trigger Types
TRIGGER_WHATSAPP_MESSAGE = "WHATSAPP_MESSAGE"
TRIGGER_USER_ACTION = "USER_ACTION"
TRIGGER_SYSTEM = "SYSTEM"
