export const WHATSAPP_WORKER_VERSION = "1.0.0";
export const WHATSAPP_INGESTION_CONTRACT_VERSION = "1.0.0";
export const OPENWA_ADAPTER_VERSION = "1.0.0";

export const MODE_FAKE = "fake";
export const MODE_REAL = "real";

export enum ConnectionState {
  DISABLED = "DISABLED",
  STARTING = "STARTING",
  WAITING_FOR_QR = "WAITING_FOR_QR",
  AUTHENTICATING = "AUTHENTICATING",
  CONNECTED = "CONNECTED",
  READY = "READY",
  RECONNECTING = "RECONNECTING",
  DEGRADED = "DEGRADED",
  LOGGED_OUT = "LOGGED_OUT",
  BLOCKED_CONFIGURATION = "BLOCKED_CONFIGURATION",
  ERROR = "ERROR",
  SHUTTING_DOWN = "SHUTTING_DOWN",
  STOPPED = "STOPPED"
}

export enum QrState {
  NOT_REQUIRED = "NOT_REQUIRED",
  WAITING = "WAITING",
  AVAILABLE = "AVAILABLE",
  EXPIRED = "EXPIRED",
  AUTHENTICATED = "AUTHENTICATED",
  FAILED = "FAILED"
}

export const DEFAULT_HOST = "127.0.0.1";
export const DEFAULT_PORT = 8010;
export const DEFAULT_SESSION_NAME = "xauusd-bot";
export const DEFAULT_TRADING_SERVICE_URL = "http://127.0.0.1:8000";
export const DEFAULT_LOCAL_API_TOKEN = "dev-local-secret-token";
export const RESET_CONFIRMATION_PHRASE = "RESET WHATSAPP SESSION";
