"""MT5 Adapter and Execution Constants."""

MT5_ADAPTER_VERSION = "1.0.0"
EXECUTION_WORKER_VERSION = "1.0.0"

# Modes
MODE_FAKE = "fake"
MODE_DRY_RUN = "dry_run"
MODE_REAL = "real"

VALID_ADAPTER_MODES = {MODE_FAKE, MODE_DRY_RUN, MODE_REAL}

# Health States
HEALTH_DISABLED = "DISABLED"
HEALTH_NOT_INSTALLED = "NOT_INSTALLED"
HEALTH_NOT_INITIALIZED = "NOT_INITIALIZED"
HEALTH_INITIALIZING = "INITIALIZING"
HEALTH_CONNECTED = "CONNECTED"
HEALTH_READY = "READY"
HEALTH_DEGRADED = "DEGRADED"
HEALTH_BLOCKED_LIVE_ACCOUNT = "BLOCKED_LIVE_ACCOUNT"
HEALTH_BLOCKED_NON_HEDGING = "BLOCKED_NON_HEDGING"
HEALTH_BLOCKED_ACCOUNT_NOT_ALLOWED = "BLOCKED_ACCOUNT_NOT_ALLOWED"
HEALTH_BLOCKED_SERVER_NOT_ALLOWED = "BLOCKED_SERVER_NOT_ALLOWED"
HEALTH_BLOCKED_SYMBOL_NOT_FOUND = "BLOCKED_SYMBOL_NOT_FOUND"
HEALTH_BLOCKED_SYMBOL_AMBIGUOUS = "BLOCKED_SYMBOL_AMBIGUOUS"
HEALTH_TRADING_NOT_ALLOWED = "TRADING_NOT_ALLOWED"
HEALTH_ERROR = "ERROR"
HEALTH_SHUTTING_DOWN = "SHUTTING_DOWN"

# Account Environments
ENV_DEMO = "DEMO"
ENV_CONTEST = "CONTEST"
ENV_REAL = "REAL"
ENV_UNKNOWN = "UNKNOWN"

# Margin Modes
MARGIN_HEDGING = "HEDGING"
MARGIN_NETTING = "NETTING"
MARGIN_EXCHANGE = "EXCHANGE"
MARGIN_UNKNOWN = "UNKNOWN"

# Symbols
CANONICAL_SYMBOL_XAUUSD = "XAUUSD"

# Job Statuses
JOB_QUEUED = "QUEUED"
JOB_RUNNING = "RUNNING"
JOB_SUCCEEDED = "SUCCEEDED"
JOB_FAILED = "FAILED"
JOB_BLOCKED = "BLOCKED"
JOB_OUTCOME_UNKNOWN = "OUTCOME_UNKNOWN"
JOB_CANCELLED = "CANCELLED"

# Batch Statuses
BATCH_QUEUED = "QUEUED"
BATCH_RUNNING = "RUNNING"
BATCH_SUCCEEDED = "SUCCEEDED"
BATCH_PARTIALLY_PLACED = "PARTIALLY_PLACED"
BATCH_FAILED = "FAILED"
BATCH_CANCELLED = "CANCELLED"

# Operations
OP_PLACE_PENDING_ORDER = "PLACE_PENDING_ORDER"
OP_MODIFY_PENDING_ORDER = "MODIFY_PENDING_ORDER"
OP_DELETE_PENDING_ORDER = "DELETE_PENDING_ORDER"
OP_MODIFY_POSITION_SLTP = "MODIFY_POSITION_SLTP"
OP_CLOSE_POSITION = "CLOSE_POSITION"
OP_CANCEL_CAMPAIGN_PENDING = "CANCEL_CAMPAIGN_PENDING"
OP_CLOSE_CAMPAIGN_POSITIONS = "CLOSE_CAMPAIGN_POSITIONS"
OP_EMERGENCY_CLOSE_ALL = "EMERGENCY_CLOSE_ALL"

# Filling Modes
FILLING_FOK = "FOK"
FILLING_IOC = "IOC"
FILLING_RETURN = "RETURN"

# Time Policies
TIME_GTC = "GTC"
TIME_DAY = "DAY"
TIME_SPECIFIED = "SPECIFIED"
TIME_SPECIFIED_DAY = "SPECIFIED_DAY"

# Partial Placement Policy
PARTIAL_KEEP_ACCEPTED = "KEEP_ACCEPTED_AND_REPORT"
PARTIAL_ROLLBACK_UNFILLED = "ROLLBACK_UNFILLED_ACCEPTED"
PARTIAL_BLOCK_REMAINING = "BLOCK_REMAINING_AFTER_FIRST_FAILURE"

# Config Defaults
DEFAULT_CLOSE_DEVIATION_POINTS = 20
DEFAULT_WORKER_POLL_INTERVAL_MS = 250
